# services:
#   sql:
#     image: mcr.microsoft.com/mssql/server:2022-latest
#     container_name: sql
#     environment:
#       ACCEPT_EULA: "Y"
#       MSSQL_SA_PASSWORD: "Password@1"
#     platform: "linux/amd64"
#     ports:
#       - "1433:1433"


# services:
#   api:
#     build:
#       context: .
#       dockerfile: API/Dockerfile
#     environment:
#       - TokenKey=mysupersecuretokenkey@1234567890abcdefghijklmnopqrstuvwxyzABCDEFGHIJKL
#     depends_on:
#       - sql
#     ports:
#       - "8080:80"

#   sql:
#     image: mcr.microsoft.com/mssql/server:2022-latest
#     container_name: sql
#     environment:
#       ACCEPT_EULA: "Y"
#       MSSQL_SA_PASSWORD: "Password@1"
#     platform: "linux/amd64"
#     ports:
#       - "1433:1433"
version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: API/Dockerfile
    environment:
      - TokenKey=mysupersecuretokenkey@1234567890abcdefghijklmnopqrstuvwxyzABCDEFGHIJKL
    ports:
      - "8080:80"
    depends_on:
      sql:
        condition: service_healthy
    restart: always


  sql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql
    environment:
      SA_PASSWORD: "Password@1"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    healthcheck:
      test: ["CMD", "sh", "-c", "exit 0"]
      interval: 10s
      timeout: 5s
      retries: 3

